### ISSUE TITLE
Deployments fail if application name has a space in it

### ISSUE THREAD

**Issue by thaiphan** [einaregilsson/beanstalk-deploy#21] opened 2020-05-03 12:29 UTC
If my Elastic Beanstalk application has a space in its name, e.g. "Application Name", and I attempt to run your script then I get the following errors:

```
Deployment failed: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
```

Do you reckon you can fix that?

**Comment by einaregilsson** [comment] 2020-05-04 08:33
Are you using the latest version? Because if I'm not mistaken I did fix that in version 10.

**Comment by thaiphan** [comment] 2020-05-04 11:24
Uh I'm not sure. I just grabbed the latest one?

I ended up using https://github.com/aws-actions/configure-aws-credentials to deploy to Elastic Beanstalk so you can close this if you can't reproduce.

**Comment by einaregilsson** [comment] 2020-05-04 12:09
Fixed in v10

**Comment by feltocraig** [comment] 2020-05-05 03:54
I'm getting the same error as above with v10.

**Comment by feltocraig** [comment] 2020-05-05 03:56
@einaregilsson I'm getting the same error as @thaiphan. I'm running v10.

**Comment by einaregilsson** [comment] 2020-05-05 08:19
@feltocraig Hmmmm. Ok, I'll look into it.

**Comment by einaregilsson** [comment] 2020-05-06 08:09
Ok, we are encoding all query string parameters but the problem is s3 paths when uploading. Encoding the path still results in an error and I can see various issues around the web with s3 sdk's having similar problems. I'll try to find how exactly they want this, encoding the path does not work, there's something around whether to encode the path for the request, for the signature, for both, I think I've tried all combinations but so far no luck :(

**Comment by hmtri1011** [comment] 2020-06-09 09:10
Hi guys, any lucks on this issue :p

**Comment by einaregilsson** [comment] 2020-06-09 10:38
No, I made quite a few attempts, with escaping the path, double escaping, escaping the path but not when it's encoded into the checksum, vice versa, etc etc. but haven't been able to find the right way to do it 🙁

**Comment by albisserAdrian** [comment] 2020-07-16 09:48
The issues still persist but I fixed it by removing the spaces in the application name. May be worth to add a warning somewhere in the README file. Besides that, it does the job flawlessly, thanks a lot.

**Comment by einaregilsson** [comment] 2020-09-24 13:08
Finally managed to fix this in v13! Closing this issue!

**Closed by einaregilsson** 2020-09-24 13:08 UTC
