### ISSUE TITLE
##[error]Deployment failed: Error: Status: 403. Message:

### ISSUE THREAD

**Issue by andresfgonz** [einaregilsson/beanstalk-deploy#28] opened 2020-06-13 22:17 UTC
im runing a single container with dockerrun.aws.json

Hello guys in receiving that error when i use a new version label
with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: vennly-player:develop
          environment_name: vennly-player-develop-env
          version_label: v1
          region: us-east-2
          deployment_package: deploy.zip

if i remove deployment_package property and use the running version as version label it works

but i need to run a new dockerrun.aws.json with an updated image name which is inside the zip file.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/4665554/84581528-c9806500-ada7-11ea-9a70-7f22ea7120d6.png">

Any Ideas?

**Comment by einaregilsson** [comment] 2020-06-15 09:54
I see you have a : in the application name. Wondering if that might be causing issues, I know we have issues uploading to S3 if there's a space in the name. Can you try with a test application without : in the name?

**Comment by omairvaiyani** [comment] 2020-06-15 15:25
We have similar problems and my application has a space within it. I think the actual issue might be the access policy to the default generated bucket by beanstalk. Other CI pipelines tend to upload to a new S3 bucket with custom policies.

**Comment by juzhiyuan** [comment] 2020-08-12 00:52
I think it's due to the Signature Version, could we support setting version like v4 for this Action?

**Comment by einaregilsson** [comment] 2020-08-12 09:04
Rebooting EC2?

**Comment by juzhiyuan** [comment] 2020-08-12 10:55
Yep, after rebooting EC2, and redeploy successfully.

**Comment by sno6** [comment] 2020-08-28 04:12
Getting this same issue.. unfortunately a reboot + redeploy isn't working

**Comment by prowave** [comment] 2020-09-10 16:21
For me, this was an illegal character "$" in the filename.

**Comment by Mdelaf** [comment] 2020-09-30 23:49
For the record:
- Whitespace (` `) in the `version_label` also produces this error
- Hashtag (`#`) in the `version_label` also produces this error
- Hyphen (`-`) in the `version-label` and/or in the `application_name` works fine

Tested on version 13.

**Comment by einaregilsson** [comment] 2020-10-01 08:27
@Mdelaf Thanks. In the next version I'll check for those and put out an error message saying what the problem is before starting the deployment.

**Comment by Mdelaf** [comment] 2020-11-03 14:45
I found that this problem also shows up when using special characters on the `version_description`.

If you set `version_description: ${{ github.event.head_commit.message }}` the deployment may fail with error 403 occasionally, depending on your latest commit description. 

In my case, I am using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for one of my projects. This commits have the following format: `<type>(<scope>): <short summary>`.  I assume that either the parenthesis - `(` and `)` - or the colon - `:` - are responsible for the problem. 

It's sad, because now I cannot have the latest commit in the version description.

It would be cool if you can have a look on this @einaregilsson

**Comment by einaregilsson** [comment] 2020-11-04 11:26
@Mdelaf I've just published version 14, which allows `:()!` in the version description. Test and see if it works for you :)

It's kind of weird, because I have to use the `encodeURIComponent()` function to encode stuff, and then handle a few special cases myself, I can't use `escape()` which escapes every special character because AWS doesn't like that, so I end up with `encodeURIComponent()` plus a few special cases...

**Comment by Mdelaf** [comment] 2020-11-05 23:16
I tested the version 14 today and it's working like a charm.

I appreciate this more than you'll ever know :grin: @einaregilsson

**Comment by mieszko4** [comment] 2020-11-20 20:40
I had this problem when using new lines in `version_description` (I put there the entire commit message)

**Comment by sam-wiser** [comment] 2021-02-13 22:07
@ symbol in the `version_label` also caused this error in v14

**Comment by einaregilsson** [comment] 2021-02-15 10:34
Ok, I guess I have some things to look at for the next version. Some restrictions are because of S3 filenames, maybe I need to remove all bad characters from the file names but still allow them in the version label.

**Comment by sam-wiser** [comment] 2021-02-15 16:08
Yep, it sure looked like the failing step was saving the S3 file with the special character in it. Looks like AWS says we should "likely" URL/hex encode a bunch of chars in the section "Characters that might require special handling": https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

Really weirdly loose guidance on that page, how are we supposed to URL encode things without being able to use %? Why not just define which characters we cant use? >_<

**Comment by einaregilsson** [comment] 2021-02-16 12:00
This should be fixed in version 15. We now change any characters that's not alphanumeric, a dash or and underscore in the S3 filename and replace it with a dash. But the version label in Elastic Beanstalk keeps all the special characters.

![Screenshot 2021-02-16 at 11 13 16](https://user-images.githubusercontent.com/557149/108059949-24144400-704e-11eb-9e70-d3b6ee6e7863.png)

This above is a version label with lots of special characters, below is the filename in S3:

![Screenshot 2021-02-16 at 11 14 19](https://user-images.githubusercontent.com/557149/108060003-368e7d80-704e-11eb-9e34-7864b2ccf797.png)

As for newlines in `version_description`, it doesn't cause an error for me, at least if I put a `"asdf\nA new line"` as the version description.  The AWS console doesn't show linebreaks for it:

![Screenshot 2021-02-16 at 11 13 16](https://user-images.githubusercontent.com/557149/108060123-63429500-704e-11eb-807d-eb74cf68d835.png)

But if you look at the source you can see the linebreaks are saved in there:

![Screenshot 2021-02-16 at 11 13 06](https://user-images.githubusercontent.com/557149/108060145-6b9ad000-704e-11eb-9508-f0bb07982797.png)

So please, everyone try their problems again with v15 and report any issues that are still happening. The one thing that you cannot do with `version_label` is put a forward slash / in there, Elastic Beanstalk itself doesn't allow that.

**Closed** 2021-02-16 12:12 UTC

**Comment by JoseLuisDelgadoCarrillo** [comment] 2024-11-28 21:16
Is anyone having the same problem as of today?
version_labels and version_descriptions don´t really appear to have issues or strange characters
